export const satFilters = [
  { group: "Last 30 Days Launches", query: "last-30-days" },
  { group: "Space Stations", query: "stations" },
  { group: "Brightest / Most Visible", query: "visual" },
  { group: "All Active Satellites", query: "active" },
  { group: "Analyst Satellites", query: "analyst" },
  {
    group: "Russian Anti Satellite Test Debris COSMOS 1408",
    query: "1982-092",
  },
  { group: "Chinese Anti Satellite Test Debris FENGYUN 1C", query: "1999-025" },
  { group: "Iridium 33 Debris", query: "iridium-33-debris" },
  { group: "COSMOS 2251 Debris", query: "cosmos-2251-debris" },
  { group: "Weather Satellites", query: "weather" },
  { group: "National Oceanic and Atmospheric Administration", query: "noaa" },
  {
    group: "Geostationary Operational Environmental Satellites",
    query: "goes",
  },
  { group: "Earth Resources", query: "resource" },
  { group: "Search and Rescue SARSAT", query: "sarsat" },
  { group: "Disaster Monitoring", query: "dmc" },
  { group: "Tracking and Data Relay Satellite System TDRSS", query: "tdrss" },
  { group: "ARGOS Data Collection System", query: "argos" },
  { group: "Planet", query: "planet" },
  { group: "Spire", query: "spire" },
  { group: "Active Geosynchronous", query: "geo" },
  { group: "Geosynchronous Protected Zone", query: "gpz" },
  { group: "Geosynchronous Protected Zone Plus", query: "gpz-plus" },
  { group: "Intelsat", query: "intelsat" },
  { group: "SES", query: "ses" },
  { group: "Intelsat", query: "intelsat" },
  { group: "Iridium", query: "iridium" },
  { group: "Iridium NEXT", query: "iridium-NEXT" },
  { group: "Starlink", query: "starlink" },
  { group: "OneWeb", query: "oneweb" },
  { group: "Iridium", query: "iridium" },
  { group: "Orbcomm", query: "orbcomm" },
  { group: "Globalstar", query: "globalstar" },
  { group: "Swarm", query: "swarm" },
  { group: "Amateur Radio", query: "amateur" },
  { group: "Experimental Comm", query: "x-comm" },
  { group: "Other Comm", query: "other-comm" },
  { group: "SatNOGS", query: "satnogs" },
  { group: "Iridium", query: "iridium" },
  { group: "Gorizont", query: "gorizont" },
  { group: "Raduga", query: "raduga" },
  { group: "Molniya", query: "molniya" },
  { group: "GNSS", query: "gnss" },
  { group: "GPS Operational", query: "gps-ops" },
  { group: "GLONASS Operational", query: "glo-ops" },
  { group: "Galileo", query: "galileo" },
  { group: "Beidou", query: "beidou" },
  {
    group: "Satellite Based Augmentation System (WAAS/EGNOS/MSAS)",
    query: "sbas",
  },
  { group: "Navy Navigation Satellite System", query: "nnss" },
  { group: "Russian LEO Navigation", query: "musson" },
  { group: "Space and Earth Science", query: "science" },
  { group: "Geodetic", query: "geodetic" },
  { group: "Engineering", query: "engineering" },
  { group: "Education", query: "education" },
  { group: "Miscellaneous Military", query: "military" },
  { group: "Radar Calibration", query: "radar" },
  { group: "Cubesats", query: "cubesat" },
  { group: "Other Satellites", query: "other" },
];
